apiVersion: v1
kind: Service
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
{{ include "chart.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      # Use named target port so pods can change numeric port safely
      targetPort: {{ ternary "mysql" (default "app" .Values.service.name) (eq .Values.flavor "db-mariadb") }}
      protocol: TCP
      name: {{ ternary "mysql" (default "app" .Values.service.name) (eq .Values.flavor "db-mariadb") }}
  selector:
{{ include "chart.selectorLabels" . | indent 4 }}
