{{- if eq .Values.flavor "db-mariadb" }}
{{- $fullname := include "chart.fullname" . -}}
{{- $ns := .Values.namespace | default .Release.Namespace -}}
{{- $secretName := .Values.auth.secretName | default (printf "%s-secret" $fullname) -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ $fullname }}
  namespace: {{ $ns }}
  labels:
{{ include "chart.labels" . | indent 4 }}
spec:
  serviceName: {{ $fullname }}
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "chart.selectorLabels" . | indent 6 }}
  template:
    metadata:
      labels:
{{ include "chart.selectorLabels" . | indent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- range .Values.imagePullSecrets }}
        - name: {{ . }}
      {{- end }}
      {{- end }}
      containers:
        - name: mariadb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MARIADB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: mariadb-root-password
            {{- if .Values.auth.database }}
            - name: MARIADB_DATABASE
              value: {{ .Values.auth.database | quote }}
            {{- end }}
            {{- if .Values.auth.username }}
            - name: MARIADB_USER
              value: {{ .Values.auth.username | quote }}
            {{- end }}
            {{- if .Values.auth.password }}
            - name: MARIADB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ $secretName }}
                  key: mariadb-password
            {{- end }}
          ports:
            - name: mysql
              containerPort: {{ .Values.service.port }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.persistentVolume.storageClass }}
        storageClassName: {{ .Values.persistentVolume.storageClass | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistentVolume.size | quote }}
{{- end }}
